[package]
name = "fmark"
version = "1.0.1"
authors = ["Vann Rollins (https://github.com/vannrr)"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "fmark"
path = "src/main.rs"
